<a href="https://colab.research.google.com/github/arthik1699/Data690_world_dev/blob/main/Data690_ProjectB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data690 - Data Visualization & Statistics
## Project Part B

* Name - Arthi Komma
* Campus id - GF89659

### Importing the pandas and plotly modules

In [ ]:
import pandas as pd
import plotly.express as px

In [ ]:
#Importing the data from the github by reading the csv file
df = pd.read_csv("https://raw.githubusercontent.com/arthik1699/Data690_world_dev/main/wdx_data.csv")

In [ ]:
#Finding how many rows and columns does the file have
df.shape

(7755, 9)

In [ ]:
#Finding the datatypes of the columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7755 entries, 0 to 7754
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    7755 non-null   int64
 1   Year          7755 non-null   int64
 2   value         7755 non-null   float64
 3   indicator     7755 non-null   object
 4   Country Code  7755 non-null   object
 5   Country Name  7755 non-null   object
 6   Region        7755 non-null   object
 7   Income Group  7755 non-null   object
 8   Lending Type  7755 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 545.4+ KB

In [ ]:
#Fetching the data of first 5 rows
df.head(5)

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,0,2016,2.778035,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
1,1,2017,2.547833,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
2,2,2018,2.384309,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
3,3,2019,2.313073,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
4,4,2020,2.303812,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA

In [ ]:
#Fetching the data of last 5 rows
df.tail(5)

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
7750,7750,2017,14236599.0,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
7751,7751,2018,14438812.0,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
7752,7752,2019,14645473.0,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
7753,7753,2020,14862927.0,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
7754,7754,2021,15092171.0,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend

In [ ]:
#Fetching the data of random 5 rows
df.sample(5)

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
6086,6086,2016,1.562935e+08,NY.ADJ.DCO2.CD,NAM,Namibia,Sub-Saharan Africa,Upper middle income,IBRD
7561,7561,2020,1.109470e+05,SP.POP.TOTL,VCT,St. Vincent and the Grenadines,Latin America & Caribbean,Upper middle income,Blend
4822,4822,2018,0.000000e+00,NY.ADJ.DFOR.CD,EST,Estonia,Europe & Central Asia,High income,Not classified
7681,7681,2020,9.890400e+06,SP.POP.TOTL,ARE,United Arab Emirates,Middle East & North Africa,High income,Not classified
2393,2393,2018,0.000000e+00,NY.ADJ.DNGY.CD,ASM,American Samoa,East Asia & Pacific,Upper middle income,Not classified

In [ ]:
#Resetting the index and dropping unwanted columns
df.reset_index(inplace=True)
df.head(5)

,index,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,0,0,2016,2.778035,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
1,1,1,2017,2.547833,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
2,2,2,2018,2.384309,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
3,3,3,2019,2.313073,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
4,4,4,2020,2.303812,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA

In [ ]:
df.drop(columns=['index','Unnamed: 0'],inplace=True)

In [ ]:
df.head()

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,2016,2.778035,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
1,2017,2.547833,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
2,2018,2.384309,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
3,2019,2.313073,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
4,2020,2.303812,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA

#### **1.Creating new dataframe to find the "GDP per capita" of some countries.**

In [ ]:
#Querying the dataframe to find the GDP per capita
df_gdp= df.query('indicator== "NY.GDP.PCAP.PP.CD"')

In [ ]:
df_gdp

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
3406,2016,1981.118069,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
3407,2017,2058.400221,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
3408,2018,2082.392197,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
3409,2019,2152.190243,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
3410,2020,2078.479082,NY.GDP.PCAP.PP.CD,AFG,Afghanistan,South Asia,Low income,IDA
...,...,...,...,...,...,...,...,...
4546,2017,2416.049969,NY.GDP.PCAP.PP.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
4547,2018,2556.793484,NY.GDP.PCAP.PP.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
4548,2019,2408.154197,NY.GDP.PCAP.PP.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
4549,2020,2251.455674,NY.GDP.PCAP.PP.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
4550,2021,2444.478237,NY.GDP.PCAP.PP.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend

In [ ]:
## Creating 2 new dataframe for the year "2016" and "2020" for visualizion.
df_gdp_2016 = df_gdp.query("Year==2016")
df_gdp_2020 = df_gdp.query("Year==2020")

In [ ]:
#Filtering the dataframe to get the info of the countries names India, United States, United Kingdom, Australia, China, Japan for the year 2016
df_gdp_2016 = df_gdp_2016[(df_gdp_2016['Country Name']=='India') | 
                          (df_gdp_2016['Country Name']=='United States') |
                          (df_gdp_2016['Country Name']=='Australia') | 
                          (df_gdp_2016['Country Name']=='United Kingdom') | 
                          (df_gdp_2016['Country Name']=='China') | 
                          (df_gdp_2016['Country Name']=='Japan')]

In [ ]:
df_gdp_2016

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
3452,2016,47255.307009,NY.GDP.PCAP.PP.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
3624,2016,13483.377267,NY.GDP.PCAP.PP.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
3869,2016,5839.864817,NY.GDP.PCAP.PP.CD,IND,India,South Asia,Lower middle income,IBRD
3916,2016,40596.968663,NY.GDP.PCAP.PP.CD,JPN,Japan,East Asia & Pacific,High income,Not classified
4497,2016,44635.299559,NY.GDP.PCAP.PP.CD,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
4503,2016,57866.744934,NY.GDP.PCAP.PP.CD,USA,United States,North America,High income,Not classified

In [ ]:
#Plotting the bar chart for GDP per capita of the year 2016 for the countries 
fig = px.bar(
    df_gdp_2016,
    x= "Country Name",
    y=	"value",
    title ="Top 7 Countries by 2016 GDP Per Capita, PPP (current international $) ",
    labels = {"value" : "GDP Per Capita, PPP ( Current International $)"},
    color = "Country Name",
    template= "plotly_dark"
)
fig.show()

In [ ]:
#Filtering the dataframe to get the info of the countries names India, United States, United Kingdom, Australia, China, Japan for the year 2016

df_gdp_2020 = df_gdp_2020[(df_gdp_2020['Country Name']=='India') | 
                          (df_gdp_2020['Country Name']=='United States') | 
                          (df_gdp_2020['Country Name']=='Australia') | 
                          (df_gdp_2020['Country Name']=='United Kingdom') |
                          (df_gdp_2020['Country Name']=='China') |
                          (df_gdp_2020['Country Name']=='Japan')]

In [ ]:
df_gdp_2020

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
3456,2020,53316.885434,NY.GDP.PCAP.PP.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
3628,2020,17189.281794,NY.GDP.PCAP.PP.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
3873,2020,6525.428052,NY.GDP.PCAP.PP.CD,IND,India,South Asia,Lower middle income,IBRD
3920,2020,42100.257691,NY.GDP.PCAP.PP.CD,JPN,Japan,East Asia & Pacific,High income,Not classified
4501,2020,46526.911865,NY.GDP.PCAP.PP.CD,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
4507,2020,63027.679527,NY.GDP.PCAP.PP.CD,USA,United States,North America,High income,Not classified

In [ ]:
#Plotting the bar chart for GDP per capita of the year 2016 for the countries
fig = px.bar(
    df_gdp_2020,
    x= "Country Name",
    y=	"value",
    title ="Top 7 Countries by 2020 GDP Per Capita, PPP (current international $) ",
    labels = {"value" : "GDP Per Capita, PPP ( Current International $)"},
    color = "Country Name",
    template= "plotly_dark"
)
fig.show()

#### **2.Creating new dataframe to find the "Mineral Depletion" of some countries.**

In [ ]:
#Querying the dataframe to find the mineral depletion values
df_mineral_depletion = df.query('indicator== "NY.ADJ.DMIN.CD"')

In [ ]:
df_mineral_depletion

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
1296,2016,3.888372e+05,NY.ADJ.DMIN.CD,AFG,Afghanistan,South Asia,Low income,IDA
1297,2017,0.000000e+00,NY.ADJ.DMIN.CD,AFG,Afghanistan,South Asia,Low income,IDA
1298,2018,0.000000e+00,NY.ADJ.DMIN.CD,AFG,Afghanistan,South Asia,Low income,IDA
1299,2019,0.000000e+00,NY.ADJ.DMIN.CD,AFG,Afghanistan,South Asia,Low income,IDA
1300,2020,0.000000e+00,NY.ADJ.DMIN.CD,AFG,Afghanistan,South Asia,Low income,IDA
...,...,...,...,...,...,...,...,...
2371,2016,1.410963e+08,NY.ADJ.DMIN.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
2372,2017,2.294158e+08,NY.ADJ.DMIN.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
2373,2018,4.455984e+08,NY.ADJ.DMIN.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
2374,2019,4.197138e+08,NY.ADJ.DMIN.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
2375,2020,5.206280e+08,NY.ADJ.DMIN.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend

In [ ]:
#Querying the dataframe to find the values for the year 2018
df_mineral_depletion_2018 = df_mineral_depletion.query("Year==2018")

In [ ]:
#Filtering the dataframe to get the info of the countries names India, United States, United Kingdom, Australia, China, Japan for the year 2018

df_mineral_depletion_2018 = df_mineral_depletion_2018[(df_mineral_depletion_2018['Country Name']=='India') | 
                                                      (df_mineral_depletion_2018['Country Name']=='United States') | 
                                                      (df_mineral_depletion_2018['Country Name']=='Australia') | 
                                                      (df_mineral_depletion_2018['Country Name']=='United Kingdom') |
                                                      (df_mineral_depletion_2018['Country Name']=='China') | 
                                                      (df_mineral_depletion_2018['Country Name']=='Japan')]

In [ ]:
df_mineral_depletion_2018

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
1348,2018,1.686135e+10,NY.ADJ.DMIN.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
1503,2018,2.049600e+10,NY.ADJ.DMIN.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
1742,2018,7.532668e+09,NY.ADJ.DMIN.CD,IND,India,South Asia,Lower middle income,IBRD
1787,2018,7.340624e+07,NY.ADJ.DMIN.CD,JPN,Japan,East Asia & Pacific,High income,Not classified
2318,2018,4.766771e+04,NY.ADJ.DMIN.CD,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
2323,2018,4.591723e+09,NY.ADJ.DMIN.CD,USA,United States,North America,High income,Not classified

In [ ]:
#Plotting the bar chart
fig = px.bar(
    df_mineral_depletion_2018,
    x= "Country Name",
    y=	"value",
    title ="Top 7 Countries by 2018 Adjusted savings: mineral depletion (current US$)",
    labels = {"value" : "2018 Adjusted savings: mineral depletion (current US$)"},
    color = "Country Name",
    template= "plotly_dark"
)
fig.show()

#### **3.Creating new dataframe to find the "Energy Depletion" of some countries.**

In [ ]:
#Querying the dataframe to find the energy depletion
df_energy_depletion = df.query('indicator== "NY.ADJ.DNGY.CD"')

In [ ]:
df_energy_depletion

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
2376,2016,1.291217e+07,NY.ADJ.DNGY.CD,AFG,Afghanistan,South Asia,Low income,IDA
2377,2017,2.152061e+07,NY.ADJ.DNGY.CD,AFG,Afghanistan,South Asia,Low income,IDA
2378,2018,2.826265e+07,NY.ADJ.DNGY.CD,AFG,Afghanistan,South Asia,Low income,IDA
2379,2019,1.789736e+07,NY.ADJ.DNGY.CD,AFG,Afghanistan,South Asia,Low income,IDA
2380,2020,1.490380e+07,NY.ADJ.DNGY.CD,AFG,Afghanistan,South Asia,Low income,IDA
...,...,...,...,...,...,...,...,...
3401,2016,1.349728e+07,NY.ADJ.DNGY.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
3402,2017,3.003109e+07,NY.ADJ.DNGY.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
3403,2018,4.002595e+07,NY.ADJ.DNGY.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
3404,2019,1.859779e+07,NY.ADJ.DNGY.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
3405,2020,1.492567e+07,NY.ADJ.DNGY.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend

In [ ]:
#Querying the dataframe to find the energy depletion for the year 2018
df_energy_depletion_2018 = df_energy_depletion.query("Year==2018")

In [ ]:
#Filtering the dataframe to get the info of the countries names India, United States, United Kingdom, Australia, China, Japan for the year 2018


df_energy_depletion_2018 = df_energy_depletion_2018[(df_energy_depletion_2018['Country Name']=='India') | 
                                                    (df_energy_depletion_2018['Country Name']=='United States') | 
                                                    (df_energy_depletion_2018['Country Name']=='Australia') | 
                                                    (df_energy_depletion_2018['Country Name']=='United Kingdom') | 
                                                    (df_energy_depletion_2018['Country Name']=='China') | 
                                                    (df_energy_depletion_2018['Country Name']=='Japan')]

In [ ]:
df_energy_depletion_2018

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
2423,2018,1.741150e+10,NY.ADJ.DNGY.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
2573,2018,9.913672e+10,NY.ADJ.DNGY.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
2812,2018,1.567818e+10,NY.ADJ.DNGY.CD,IND,India,South Asia,Lower middle income,IBRD
2852,2018,3.433261e+08,NY.ADJ.DNGY.CD,JPN,Japan,East Asia & Pacific,High income,Not classified
3348,2018,1.710559e+10,NY.ADJ.DNGY.CD,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
3353,2018,7.352997e+10,NY.ADJ.DNGY.CD,USA,United States,North America,High income,Not classified

In [ ]:
#Plotting the pie chart
fig = px.pie(
    df_energy_depletion_2018,
    names="Country Name", 
    values="value", 
    title="Top 7 Countries by 2018 Adjusted savings: energy depletion (current US$)", 
    color="Country Name", 
    template="plotly_dark"
)

fig.update_layout(showlegend=True)

fig.update_traces(textposition='inside', textinfo='label+percent+value')

fig.show()

#### **4.Creating new dataframe to find the "Forest Depletion" of some countries.**

In [ ]:
#Querying the dataframe to find the forest depletion values
df_forest_depletion = df.query('indicator== "NY.ADJ.DFOR.CD"')

In [ ]:
df_forest_depletion

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
4551,2016,5.182773e+07,NY.ADJ.DFOR.CD,AFG,Afghanistan,South Asia,Low income,IDA
4552,2017,4.399931e+07,NY.ADJ.DFOR.CD,AFG,Afghanistan,South Asia,Low income,IDA
4553,2018,4.432144e+07,NY.ADJ.DFOR.CD,AFG,Afghanistan,South Asia,Low income,IDA
4554,2019,5.128052e+07,NY.ADJ.DFOR.CD,AFG,Afghanistan,South Asia,Low income,IDA
4555,2020,6.259046e+07,NY.ADJ.DFOR.CD,AFG,Afghanistan,South Asia,Low income,IDA
...,...,...,...,...,...,...,...,...
5467,2016,6.858139e+08,NY.ADJ.DFOR.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
5468,2017,6.570261e+08,NY.ADJ.DFOR.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
5469,2018,4.039977e+08,NY.ADJ.DFOR.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
5470,2019,4.368659e+08,NY.ADJ.DFOR.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
5471,2020,4.751844e+08,NY.ADJ.DFOR.CD,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend

In [ ]:
#Querying the dataframe to find the values for the year 2016
df_forest_depletion_2016 = df_forest_depletion.query("Year==2016")

In [ ]:
#Filtering the dataframe to get the info of the countries names India, United States, United Kingdom, Australia, China, Japan for the year 2016


df_forest_depletion_2016 = df_forest_depletion_2016[(df_forest_depletion_2016['Country Name']=='India') | 
                                                    (df_forest_depletion_2016['Country Name']=='United States') | 
                                                    (df_forest_depletion_2016['Country Name']=='Australia') | 
                                                    (df_forest_depletion_2016['Country Name']=='United Kingdom') |
                                                    (df_forest_depletion_2016['Country Name']=='China') | 
                                                    (df_forest_depletion_2016['Country Name']=='Japan')]

In [ ]:
df_forest_depletion_2016

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
4586,2016,0.000000e+00,NY.ADJ.DFOR.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
4721,2016,0.000000e+00,NY.ADJ.DFOR.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
4925,2016,6.837083e+09,NY.ADJ.DFOR.CD,IND,India,South Asia,Lower middle income,IBRD
4965,2016,0.000000e+00,NY.ADJ.DFOR.CD,JPN,Japan,East Asia & Pacific,High income,Not classified
5424,2016,0.000000e+00,NY.ADJ.DFOR.CD,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
5427,2016,0.000000e+00,NY.ADJ.DFOR.CD,USA,United States,North America,High income,Not classified

In [ ]:
#Plotting the Choropleth chart
import plotly.express as px
fig = px.choropleth(df_forest_depletion_2016,
                    locations ='Country Name',
                    locationmode ='country names',
                    color ='value',
                    template ='plotly_dark',
                    title ="Top 7 Countries by 2016 Adjusted savings: forest depletion (current US$)")
fig.show()

#### **5.Creating new dataframe to find the "Carbon dioxide Depletion" of some countries.**

In [ ]:
#Finding the unique values in the indicator column
df["indicator"].unique()

array(['SP.POP.GROW', 'NY.ADJ.DMIN.CD', 'NY.ADJ.DNGY.CD',
       'NY.GDP.PCAP.PP.CD', 'NY.ADJ.DFOR.CD', 'NY.ADJ.DCO2.CD',
       'SP.POP.TOTL'], dtype=object)

In [ ]:
#Considering three unique values of the indicator column and listing them into a seperate variale
my_indicators = ["SP.POP.GROW", "SP.POP.TOTL", "NY.ADJ.DCO2.CD"]

#Filtering the data based on the list created
df1 = df[df["indicator"].isin(my_indicators)]

In [ ]:
df1

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,2016,2.778035e+00,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
1,2017,2.547833e+00,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
2,2018,2.384309e+00,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
3,2019,2.313073e+00,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
4,2020,2.303812e+00,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
...,...,...,...,...,...,...,...,...
7750,2017,1.423660e+07,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
7751,2018,1.443881e+07,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
7752,2019,1.464547e+07,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
7753,2020,1.486293e+07,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend
7754,2021,1.509217e+07,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend

In [ ]:
#querying the data frame for the year 2016
df2 = df1.query('Year == 2016')

In [ ]:
df2

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,2016,2.778035e+00,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
6,2016,-1.598804e-01,SP.POP.GROW,ALB,Albania,Europe & Central Asia,Upper middle income,IBRD
12,2016,2.051352e+00,SP.POP.GROW,DZA,Algeria,Middle East & North Africa,Lower middle income,IBRD
18,2016,-1.201309e-01,SP.POP.GROW,ASM,American Samoa,East Asia & Pacific,Upper middle income,Not classified
24,2016,-8.989809e-01,SP.POP.GROW,AND,Andorra,Europe & Central Asia,High income,Not classified
...,...,...,...,...,...,...,...,...
7725,2016,1.075160e+05,SP.POP.TOTL,VIR,Virgin Islands (U.S.),Latin America & Caribbean,High income,Not classified
7731,2016,4.367088e+06,SP.POP.TOTL,PSE,West Bank and Gaza,Middle East & North Africa,Lower middle income,Not classified
7737,2016,2.716821e+07,SP.POP.TOTL,YEM,"Yemen, Rep.",Middle East & North Africa,Low income,IDA
7743,2016,1.636345e+07,SP.POP.TOTL,ZMB,Zambia,Sub-Saharan Africa,Low income,IDA
7749,2016,1.403034e+07,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend

In [ ]:
#Filtering the dataframe to get the info of the countries names India, United States, United Kingdom, Australia, China, Japan for the year 2016


df_carbon_depletion_2016 = df2[(df2['Country Name']=='India') | 
                               (df2['Country Name']=='United States') | 
                               (df2['Country Name']=='Australia') | 
                               (df2['Country Name']=='United Kingdom') | 
                               (df2['Country Name']=='China') | 
                               (df2['Country Name']=='Japan')]

In [ ]:
df_carbon_depletion_2016

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
60,2016,1.561940e+00,SP.POP.GROW,AUS,Australia,East Asia & Pacific,High income,Not classified
246,2016,5.730509e-01,SP.POP.GROW,CHN,China,East Asia & Pacific,Upper middle income,IBRD
528,2016,1.090459e+00,SP.POP.GROW,IND,India,South Asia,Lower middle income,IBRD
582,2016,-5.113742e-02,SP.POP.GROW,JPN,Japan,East Asia & Pacific,High income,Not classified
1224,2016,7.578745e-01,SP.POP.GROW,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
1230,2016,7.246761e-01,SP.POP.GROW,USA,United States,North America,High income,Not classified
5517,2016,1.376386e+10,NY.ADJ.DCO2.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
5652,2016,3.518148e+11,NY.ADJ.DCO2.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
5866,2016,7.826432e+10,NY.ADJ.DCO2.CD,IND,India,South Asia,Lower middle income,IBRD
5906,2016,4.199097e+10,NY.ADJ.DCO2.CD,JPN,Japan,East Asia & Pacific,High income,Not classified
6399,2016,1.358212e+10,NY.ADJ.DCO2.CD,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
6404,2016,1.752437e+11,NY.ADJ.DCO2.CD,USA,United States,North America,High income,Not classified
6519,2016,2.419091e+07,SP.POP.TOTL,AUS,Australia,East Asia & Pacific,High income,Not classified
6705,2016,1.387790e+09,SP.POP.TOTL,CHN,China,East Asia & Pacific,Upper middle income,IBRD
6987,2016,1.324517e+09,SP.POP.TOTL,IND,India,South Asia,Lower middle income,IBRD
7041,2016,1.270760e+08,SP.POP.TOTL,JPN,Japan,East Asia & Pacific,High income,Not classified
7683,2016,6.561159e+07,SP.POP.TOTL,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
7689,2016,3.230718e+08,SP.POP.TOTL,USA,United States,North America,High income,Not classified

In [ ]:
#Creating a pivot table for better visualization

df_carbon_depletion_2016_pivot = pd.pivot_table(df_carbon_depletion_2016, 
                                                values = 'value', 
                                                index=['Country Code', 'Country Name','Year'], 
                                                columns = 'indicator').reset_index()

df_carbon_depletion_2016_pivot

indicator,Country Code,Country Name,Year,NY.ADJ.DCO2.CD,SP.POP.GROW,SP.POP.TOTL
0,AUS,Australia,2016,1.376386e+10,1.561940,2.419091e+07
1,CHN,China,2016,3.518148e+11,0.573051,1.387790e+09
2,GBR,United Kingdom,2016,1.358212e+10,0.757874,6.561159e+07
3,IND,India,2016,7.826432e+10,1.090459,1.324517e+09
4,JPN,Japan,2016,4.199097e+10,-0.051137,1.270760e+08
5,USA,United States,2016,1.752437e+11,0.724676,3.230718e+08

In [ ]:
#Plotting the scatter plot for the year 2016
fig = px.scatter(
    df_carbon_depletion_2016_pivot,
    x="SP.POP.GROW",
    y="NY.ADJ.DCO2.CD", 
    title="Top 7 Countries by 2016 Adjusted savings: carbon dioxide depletion (current US$)", 
    color="Country Name", 
    template="plotly_dark",
    #size = "Country Name",
    #hover_name = "SP.POP.GROW"
)

fig.update_layout(showlegend=True)
fig.update_layout(
    xaxis_title="Population growth (annual %)",
    yaxis_title="Adjusted savings: carbon dioxide damage (current US$)",)


fig.show()

In [ ]:
#Querying the data frame for the year 2020
df3 = df1.query('Year == 2020')

In [ ]:
df3

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
4,2020,2.303812e+00,SP.POP.GROW,AFG,Afghanistan,South Asia,Low income,IDA
10,2020,-5.742070e-01,SP.POP.GROW,ALB,Albania,Europe & Central Asia,Upper middle income,IBRD
16,2020,1.836534e+00,SP.POP.GROW,DZA,Algeria,Middle East & North Africa,Lower middle income,IBRD
22,2020,-2.081279e-01,SP.POP.GROW,ASM,American Samoa,East Asia & Pacific,Upper middle income,Not classified
28,2020,1.541341e-01,SP.POP.GROW,AND,Andorra,Europe & Central Asia,High income,Not classified
...,...,...,...,...,...,...,...,...
7729,2020,1.062900e+05,SP.POP.TOTL,VIR,Virgin Islands (U.S.),Latin America & Caribbean,High income,Not classified
7735,2020,4.803269e+06,SP.POP.TOTL,PSE,West Bank and Gaza,Middle East & North Africa,Lower middle income,Not classified
7741,2020,2.982597e+07,SP.POP.TOTL,YEM,"Yemen, Rep.",Middle East & North Africa,Low income,IDA
7747,2020,1.838396e+07,SP.POP.TOTL,ZMB,Zambia,Sub-Saharan Africa,Low income,IDA
7753,2020,1.486293e+07,SP.POP.TOTL,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend

In [ ]:
#Filtering the dataframe to get the info of the countries names India, United States, United Kingdom, Australia, China, Japan for the year 2016


df_carbon_depletion_2020 = df3[(df3['Country Name']=='India') | 
                               (df3['Country Name']=='United States') | 
                               (df3['Country Name']=='Australia') | 
                               (df3['Country Name']=='United Kingdom') | 
                               (df3['Country Name']=='China') | 
                               (df3['Country Name']=='Japan')]

In [ ]:
df_carbon_depletion_2020

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
64,2020,1.282933e+00,SP.POP.GROW,AUS,Australia,East Asia & Pacific,High income,Not classified
250,2020,2.380409e-01,SP.POP.GROW,CHN,China,East Asia & Pacific,Upper middle income,IBRD
532,2020,9.894138e-01,SP.POP.GROW,IND,India,South Asia,Lower middle income,IBRD
586,2020,-2.941946e-01,SP.POP.GROW,JPN,Japan,East Asia & Pacific,High income,Not classified
1228,2020,3.654094e-01,SP.POP.GROW,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
1234,2020,9.612011e-01,SP.POP.GROW,USA,United States,North America,High income,Not classified
5521,2020,1.581482e+10,NY.ADJ.DCO2.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
5656,2020,4.291902e+11,NY.ADJ.DCO2.CD,CHN,China,East Asia & Pacific,Upper middle income,IBRD
5870,2020,9.580785e+10,NY.ADJ.DCO2.CD,IND,India,South Asia,Lower middle income,IBRD
5910,2020,4.358677e+10,NY.ADJ.DCO2.CD,JPN,Japan,East Asia & Pacific,High income,Not classified
6403,2020,1.250699e+10,NY.ADJ.DCO2.CD,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
6408,2020,1.945130e+11,NY.ADJ.DCO2.CD,USA,United States,North America,High income,Not classified
6523,2020,2.569327e+07,SP.POP.TOTL,AUS,Australia,East Asia & Pacific,High income,Not classified
6709,2020,1.411100e+09,SP.POP.TOTL,CHN,China,East Asia & Pacific,Upper middle income,IBRD
6991,2020,1.380004e+09,SP.POP.TOTL,IND,India,South Asia,Lower middle income,IBRD
7045,2020,1.262610e+08,SP.POP.TOTL,JPN,Japan,East Asia & Pacific,High income,Not classified
7687,2020,6.708100e+07,SP.POP.TOTL,GBR,United Kingdom,Europe & Central Asia,High income,Not classified
7693,2020,3.315011e+08,SP.POP.TOTL,USA,United States,North America,High income,Not classified

In [ ]:
#Creating the pivot table for better visualization

df_carbon_depletion_2020_pivot = pd.pivot_table(df_carbon_depletion_2020, 
                                                values = 'value', 
                                                index=['Country Code', 'Country Name','Year'], 
                                                columns = 'indicator').reset_index()

df_carbon_depletion_2020_pivot

indicator,Country Code,Country Name,Year,NY.ADJ.DCO2.CD,SP.POP.GROW,SP.POP.TOTL
0,AUS,Australia,2020,1.581482e+10,1.282933,2.569327e+07
1,CHN,China,2020,4.291902e+11,0.238041,1.411100e+09
2,GBR,United Kingdom,2020,1.250699e+10,0.365409,6.708100e+07
3,IND,India,2020,9.580785e+10,0.989414,1.380004e+09
4,JPN,Japan,2020,4.358677e+10,-0.294195,1.262610e+08
5,USA,United States,2020,1.945130e+11,0.961201,3.315011e+08

In [ ]:
#Plotting the scatter plot for the year 2020

fig = px.scatter(
    df_carbon_depletion_2020_pivot,
    x="SP.POP.GROW",
    y="NY.ADJ.DCO2.CD", 
    title="Top 7 Countries by 2020 Adjusted savings: carbon dioxide depletion (current US$)", 
    color="Country Name", 
    template="plotly_dark",
    size = "SP.POP.TOTL",
    hover_name = "SP.POP.TOTL"
)

fig.update_layout(showlegend=True)
fig.update_layout(
    xaxis_title="Population growth (annual %)",
    yaxis_title="Adjusted savings: carbon dioxide damage (current US$)",)


fig.show()